Frontend:
    resource: "@FrontendFrontendBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@BackendBackendBundle/Resources/config/routing.yml"
    prefix:   /user

BackEnd:
    resource: "@BackendBackendBundle/Resources/config/routing_fos.yml"
    prefix:   /admin