frontend_frontend:
    resource: "@FrontendFrontendBundle/Resources/config/routing.yml"
    prefix:   /

backend_backend:
    resource: "@BackendBackendBundle/Resources/config/routing.yml"
    prefix:   /

garde_frontend:
    resource: "@GardeFrontendBundle/Resources/config/routing.yml"
    prefix:   /

garde_backend:
    resource: "@GardeBackendBundle/Resources/config/routing.yml"
    prefix:   /

