<?php

namespace Backend\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRepository extends EntityRepository
{
}
