<?php

namespace Backend\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends EntityRepository
{
}
